Repository auth0/node-jwks-rsa, pull requests merged in 2020-02, with the labels that each got.

#123 Modify Cache Defaults
  README.md
  src/JwksClient.js
  src/wrappers/cache.js
  tests/cache.tests.js
  tests/rateLimit.tests.js
Labels: CH: Changed, small

#128 Send the explicit commit SHA to Codecov
  .circleci/config.yml
Labels: CH: Fixed, tiny

#125 Add proxy option to jwksClient
  README.md
  index.d.ts
  src/JwksClient.js
  tests/jwksClient.tests.js
Labels: CH: Added

#129 Fix Linting
  .circleci/config.yml
  .eslintrc
  package-lock.json
  package.json
  src/JwksClient.js
  src/integrations/passport.js
  src/utils.js
  tests/cache.tests.js
  tests/jwksClient.tests.js
  tests/koa.tests.js
  tests/passport.tests.js
Labels: CH: Fixed, tiny
