Repository auth0/node-jwks-rsa, pull requests merged in 2020-12, with the labels that each got.

#202 Provides an alternative source for keysets
  README.md
  index.d.ts
  src/JwksClient.js
  src/utils.js
  src/wrappers/index.js
  src/wrappers/interceptor.js
  tests/jwksClient.tests.js
  tests/mocks/jwks.json
Labels: enhancement

#206 Add types for agent options used by ExpressJwtOptions
  index.d.ts
  package-lock.json
  package.json
Labels: CH: Fixed, review:tiny

#208 Bump Axios to ^0.21.1
  package-lock.json
  package.json
Labels: CH: Security

#209 Release v1.12.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: review:tiny
