Repository auth0/node-jwks-rsa, pull requests merged in 2020-04, with the labels that each got.

#135 Migrate from Deprecated Request Lib
  index.d.ts
  package-lock.json
  package.json
  src/JwksClient.js
  src/wrappers/request.js
  tests/jwksClient.tests.js
Labels: CH: Changed, small

#132 Added timeout with default value of 30s
  README.md
  index.d.ts
  src/JwksClient.js
  src/wrappers/request.js
Labels: CH: Added

#137 Update package-lock.json
  package-lock.json
Labels: tiny
