Repository auth0/node-jwks-rsa, pull requests merged in 2020-08, with the labels that each got.

#157 Update express-jwt
  examples/express-demo/package.json
  package-lock.json
  package.json
  tests/express.es5.tests.js
Labels: tiny

#161 Add promisified methods to JwksClient
  README.md
  src/JwksClient.js
  tests/jwksClient.tests.js
Labels: CH: Added, medium

#153 Use axios url parameter instead of baseURL
  src/wrappers/request.js
Labels: CH: Fixed

#162 Release v1.9.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: tiny
