Repository auth0/node-jwks-rsa, pull requests merged in 2020-01, with the labels that each got.

#117 Release 1.6.1
  CHANGELOG.md
  package-lock.json
  package.json
Labels: tiny

#116 Handling case when Jwk doesn't have 'use' parameter
  src/JwksClient.js
  tests/jwksClient.tests.js
Labels: CH: Changed

#119 Add alias for obtaining the public key
  README.md
  index.d.ts
  src/JwksClient.js
  tests/jwksClient.tests.js
Labels: CH: Fixed, small

#120 Release 1.6.2
  CHANGELOG.md
Labels: tiny
