Repository auth0/node-jwks-rsa, pull requests merged in 2020-09, with the labels that each got.

#176 Fixing proxy on Axios
  package-lock.json
  package.json
  src/wrappers/request.js
  tests/jwksClient.tests.js
Labels: CH: Fixed, bug

#177 Fix caching and rateLimiting on getSigningKeyAsync
  src/JwksClient.js
Labels: CH: Fixed

#168 getSigningKeys return algorithm
  src/JwksClient.js
Labels: CH: Added

#186 Update CHANGELOG.md
  CHANGELOG.md
Labels: tiny
