Repository auth0/node-jwks-rsa, pull requests merged in 2021-02, with the labels that each got.

#221 jfrog -> npmjs
  package-lock.json
Labels: review:tiny

#220 Add alg to SigningKey types
  index.d.ts
Labels: CH: Added

#216 Import default Axios instance. fix #215.
  src/wrappers/request.js
Labels: bug

#222 Migrate from callbacks to async/await
  README.md
  index.d.ts
  package.json
  src/JwksClient.js
  src/integrations/express.js
  src/integrations/hapi.js
  src/integrations/koa.js
  src/integrations/passport.js
  src/wrappers/cache.js
  src/wrappers/interceptor.js
  src/wrappers/rateLimit.js
  tests/cache.tests.js
  tests/jwksClient.tests.js
  tests/koa.tests.js
  tests/mocks/jwks.json
  tests/passport.tests.js
  tests/rateLimit.tests.js
Labels: CH: Breaking Change, CH: Changed

#218 Simplify request wrapper
  README.md
  index.d.ts
  package-lock.json
  package.json
  src/JwksClient.js
  src/integrations/express.js
  src/integrations/hapi.js
  src/integrations/koa.js
  src/integrations/passport.js
  src/wrappers/cache.js
  src/wrappers/interceptor.js
  src/wrappers/rateLimit.js
  src/wrappers/request.js
  tests/cache.tests.js
  tests/jwksClient.tests.js
  tests/koa.tests.js
  tests/mocks/jwks.json
  tests/passport.tests.js
  tests/rateLimit.tests.js
  tests/request.tests.js
Labels: CH: Added, CH: Breaking Change, CH: Changed
